language: node_js
node_js:
  - lts/*
install:
  - npm i
script:
  - sh ./deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: adaacf7fb30284d5218f9032c733227db8cfab0b
  keep_history: true
  on:
    branch: master
